const fs = require('fs');
const path = require('path');

const styleDir = path.join(__dirname, '..', 'style');
const styleIndex = path.join(styleDir, 'index.css');

if (!fs.existsSync(styleDir)) {
  fs.mkdirSync(styleDir, { recursive: true });
}

if (!fs.existsSync(styleIndex)) {
  fs.writeFileSync(
    styleIndex,
    '/* generated by build */\n@import url("../src/style/index.css");\n'
  );
}
